name = "swift-complexity-api"
compatibility_date = "2024-12-01"

# Container configuration
[build]
command = "docker build -t swift-complexity-api -f Dockerfile ../.."

[[services]]
name = "swift-complexity-api"
binding = "API"

[env.production]
name = "swift-complexity-api"
route = "api.swift-complexity.fummicc1.dev/*"

# Environment variables for production
[env.production.vars]
LOG_LEVEL = "info"
